blank_issues_enabled: true
contact_links:
  - name: preCICE Discourse Forum
    url: https://precice.discourse.group
    about: For usage questions, please ask on the preCICE Discourse forum instead of opening a GitHub issue.
